### ISSUE TITLE
mouseUp event at input-field out of modal closes modal

### ISSUE THREAD

**Issue by dhffdh** [yjose/reactjs-popup#100]
If you pick/select a Input-field and hold the cursor outside the modal, the modal close down

**Comment by dhffdh** [comment]
For example, if I allocate a value in the input, then the modal closes

**Comment by dhffdh** [comment]
ex: https://codesandbox.io/embed/reactjs-popup-bug-dg6om

**Comment by dhffdh** [comment]
New observation: if you add the property "inline", then this bug is not observed

**Comment by dhffdh** [comment]
New observation: if you add the property inline, then this bug is not observed

**Comment by yjose** [comment]
Hi @dhffdh, this is the default behavior because `closeOnDocumentClick` prop is true by default you can prevent closing the modal by adding `closeOnDocumentClick ={false}` 
check  Component API page : https://react-popup.elazizi.com/component-api/

**Comment by dhffdh** [comment]
> Hi @dhffdh, this is the default behavior because `closeOnDocumentClick` prop is true by default you can prevent closing the modal by adding `closeOnDocumentClick ={false}`
> check Component API page : https://react-popup.elazizi.com/component-api/

But i dont want disable this function. I want close popup by onClick outside , but not mouseUp event.

**Comment by dhffdh** [comment]
same bug https://github.com/Semantic-Org/Semantic-UI-React/pull/3582
