### ISSUE TITLE
closeOnDocumentClick doesn't work if click is on a button

### ISSUE THREAD

**Issue by reactedlau** [yjose/reactjs-popup#101]
If the user clicks on a button, the popup isn't dismissed even if `closeOnDocumentClick` is set to true. That's because the button will process the event first and swallow it. This can be fixed by changing this line:

https://github.com/yjose/reactjs-popup/blob/master/src/index.js#L354

to use `onClickCapture` to handle the click on the capture phase rather than the bubble phase. I believe this is the expected behavior. Try this on any native popup up. A click on a button or other UI control will dismiss a native popup.

**Comment by yjose** [comment]
fixed on v2
