### ISSUE TITLE
Trigger within table alters page on popup (adds phantom cell to table)

### ISSUE THREAD

**Issue by leonheess** [yjose/reactjs-popup#102]
### Version
`"reactjs-popup": "^1.4.1"`

### Test Case
https://codesandbox.io/s/reactjs-popup-issue-xk0t3

### Expected Behavior
Modal/Popup comes up without any changes to the visible page behind

### Actual Behavior
A new cell is created and remains visible until the modal is closed

**Full page demo: https://xk0t3.codesandbox.io/**

**Comment by yjose** [comment]
fixed : https://codesandbox.io/s/reactjs-popup-issue-forked-96zis?file=/src/index.js
