### ISSUE TITLE
font-size is inherited from parent element

### ISSUE THREAD

**Issue by gajus** [yjose/reactjs-popup#103]
### Version

1.4.1

### Test Case

https://codesandbox.io/s/reactjs-popup-issue-template-hz93r

### Expected Behavior

The actual tooltip element should be parent to <body> and absolutely positioned relative to the trigger element to avoid parent container bleeding styles to the contents of the tooltip.

### Actual Behavior

The actual tooltip element is placed next to the trigger element, causing inheritance of the parent element styles.

**Comment by avin-kavish** [comment]
your span is inside h2 too. It will inherit the styles regardless of whether it is inside the span or next to it.
