### ISSUE TITLE
Issue with staying on top and mouseover menu items

### ISSUE THREAD

**Issue by unhedged79** [yjose/reactjs-popup#11]
Installed this and works perfectly in most of my site's components, except for a chatroom component whose css renders the page using 'vh' and calculations for page height. I think that is the only difference in css between the chat component and the others, and there is no z-index whatsoever in the chat component.

I tried added styling of 'z-index': "100", etc to the contentStyle prop, but it still won't pop out on top.
Also, the mouseover for the menu items doesn't work on this page either. Obviously the lower menu items don't even show up, but the top menu item loses the hover just a few pixels in to the area.

This is what it normally looks like:
![screen shot 2018-04-16 at 12 46 35 pm](https://user-images.githubusercontent.com/37581587/38823525-97277acc-4174-11e8-8167-0f2da00ad7f4.png)

And this is how the popup renders on the chat page (which doesn't have any z-index in css):
![screen shot 2018-04-16 at 12 46 17 pm](https://user-images.githubusercontent.com/37581587/38823539-a9be109c-4174-11e8-99b9-d8b1dd7eb9f2.png)

Also, the "View Profile" mouseover doesn't work in this one, but it does in all the others...

**Comment by yjose** [comment]
Hi friend,
Can you help me determine your problem by using a  codesandbox example https://codesandbox.io/s/n5q4zqw2n0
Thanks

**Comment by unhedged79** [comment]
Issue was resolved - very prompt response from author.

My div was set as position: relative, and changing it to position: static allowed the popup to float on top again. Thanks!
