### ISSUE TITLE
popup_show_trigger Error

### ISSUE THREAD

**Issue by m-korkut** [yjose/reactjs-popup#111]
I don't want to use trigger , ı use react state but ı get this error  **Cannot read property 'popup_show_trigger' of undefined**  
				 				 
	   `  <Popup
                          open={this.state.myPopupisOpen}
                          onClose={() => {
                                  this.setState({this.state.myPopupisOpen:false})
                          }}
                         modal
                         closeOnDocumentClick
                         {/*trigger :I don't want to use trigger*/}
                        >
                    <div className="panel panel-default">
                        <div className="panel-heading">
                            <h3>{this.state.popupHeader}</h3>
                            <a    href="javascript:;"
                                    onClick={() =>  this.setState(this.state.myPopupisOpen:false)}
                                    >
                                        <i className="fa fa-times"/>
                               </a>
                        </div>
                        <div className="panel-body">
                            {this.state.popupText}
                        </div>
                    </div>
                </Popup>`

I would appreciate if you help .

**Comment by yjose** [comment]
hi @m-korkut, not sure about your problem. try to use  https://react-popup.elazizi.com/controlled-popup 
or please  use https://codesandbox.io/s/n5q4zqw2n0 to illustrates your  problem.

**Comment by m-korkut** [comment]
I found the problem, The problem stems from a different location,we can delete this question.
Thanks thank you for your help
