### ISSUE TITLE
styled-components support

### ISSUE THREAD

**Issue by ron4ex** [yjose/reactjs-popup#118]
### Version
1.4.2

### Test Case
https://codesandbox.io/s/styled-js-popup-dnknr

### Expected Behavior
`styled-components` should be able to wrap the component to override styles.

### Actual Behavior
Style overriding fails using `styled-components`. I think it would be fair to say that it is a generic usecase these days. `className` prop doesn't behave like normal `className`. It behaves more like a `customClassName`. I think both props can be supported by keeping `className` as it is. So it can be used by other libs.

**Comment by alekslario** [comment]
> ### Version
> 1.4.2
> 
> ### Test Case
> https://codesandbox.io/s/styled-js-popup-dnknr
> 
> ### Expected Behavior
> `styled-components` should be able to wrap the component to override styles.
> 
> ### Actual Behavior
> Style overriding fails using `styled-components`. I think it would be fair to say that it is a generic usecase these days. `className` prop doesn't behave like normal `className`. It behaves more like a `customClassName`. I think both props can be supported by keeping `className` as it is. So it can be used by other libs.

workaround

```
const StyledPopup = styled(({className, ...props})=><Popup contentStyle={className} {...props}/>)`
  left: 0;
`;
```

**Comment by KumarAbhirup** [comment]
The `trigger` prop accepts only a JSX Element and not a Styled Components. Any workaround here?

**Comment by yjose** [comment]
starting from v2 we support styling with `styled-components` https://codesandbox.io/s/styled-js-popup-forked-uk94g?file=/src/index.js

docs => https://react-popup.elazizi.com/styled-styling

**Comment by kanapka94** [comment]
But styled-component inside `trigger` is breaking Trigger position :|
