### ISSUE TITLE
Unable to trigger Tooltip

### ISSUE THREAD

**Issue by gajus** [yjose/reactjs-popup#119]
### Test Case

https://codesandbox.io/s/reactjs-popup-issue-template-vdusb

### Expected Behavior

Tooltip.

### Actual Behavior

Popup.

**Comment by yjose** [comment]
Hi @gajus, this is the default behavior when you don't add the `trigger` prop. a tooltip should be always related to a trigger element ( we need to calculate position).

**Comment by gajus** [comment]
I was expecting that it will just use parent element position.

I can just provide a dummy trigger.

The original intent was to have a reactjs-popup as a dropdown for a search input. I guess Input element could be added as trigger.

**Comment by yjose** [comment]
Yeah correct any Html element can be a trigger
