### ISSUE TITLE
not compatible with Internet Explorer 11 

### ISSUE THREAD

**Issue by unhedged79** [yjose/reactjs-popup#12]
Is there a known bug with reactjs-popup and Internet Explorer 11? Neither the menu nor the tooltip works, and crashes the site with error:
"Object doesn't support property or method 'includes' "

Seems to be a known issue as IE 11 doesn't support includes and to get around it people change their code to use window.indexOf?

**Comment by zhuangya** [comment]
related stackoverflow thread: https://stackoverflow.com/a/31119502/553523
maybe add browser target in `.babelrc` since this project has already using `babel-preset-env`?
