### ISSUE TITLE
Crashes on hover with FontAwesome icons

### ISSUE THREAD

**Issue by raRaRa** [yjose/reactjs-popup#128]
### Version
1.5.0

### Test Case
https://codesandbox.io/s/vigilant-kare-v48kh
Note how the app crashes if you hover the cursor over the question circle. Works great if the trigger has a div instead of FontAwesome icon.

### Expected Behavior
I excepted it not to crash. Unsure if this is a problem with how this library tries to handle the children within the trigger.

### Actual Behavior
Show tooltip without crashing

**Comment by raRaRa** [comment]
I can confirm that this only crashes on version 1.5.0, but works on version 1.4.2.

However, wrapping the FontAwesome icon within a div container seems to fix the problem.

```
      <Popup
        trigger={<div><FontAwesomeIcon icon={faPoo} fixedWidth /></div>}
        position="top center"
        on="hover"
      >
        <small className="small">This is a message</small>
      </Popup>
```

**Comment by raRaRa** [comment]
I've been digging a bit deeper, this crash seems to happen when the trigger is a functional component. This is the warning I get from React:

`Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?`

**Comment by yjose** [comment]
correct @raRaRa, this is related to the depreciation of `findDom` function.  from the version 1.5.0 and above you need to forward ref for  trigger functions like the following : 
```jsx
// need to forward ref if you are trying to use a function trigger with React Component
// Works
  <Popup
    trigger={open => (
      <button className="button">Trigger - {open ? "Opened" : "Closed"}</button>
    )}
    position="right center"
    closeOnDocumentClick
  >
    <span> Popup content </span>
  </Popup>
// works too
const CustomButton = React.forwardRef(({open , ...props}, ref) => (
  <button className="button" ref={ref} {...props}>
    Trigger - {props.open ? 'Opened' : 'Closed'}
  </button>
));
<Popup
    trigger={open => <CustomButton  open={open}/>}
    position="right center"
    closeOnDocumentClick
  >
    <span> Popup content </span>
</Popup>
```

Let’s me know if your problem still consists

**Comment by raRaRa** [comment]
Hmm, so if I want to use `<FontAwesomeIcon>` as a trigger, I need to wrap it with `React.forwardRef`?

E.g.:
```
const CustomFontAwesomeIcon = React.forwardRef(({open , ...props}, ref) => (
  <FontAwesomeIcon ref={ref} {...props}>
    Some information text
  </FontAwesomeIcon>
));
```

**Comment by yjose** [comment]
Unfortunately, this won’t work correctly because FontAwesomeIcon dosnt supports refs, so you cannot pass `ref` as a prop.
https://github.com/FortAwesome/react-fontawesome/blob/master/src/components/FontAwesomeIcon.js

**Comment by raRaRa** [comment]
Damn. Seems like a big limitation on this library :( I would expect it to work with any trigger. I guess I'll work around with putting FontAwesomeIcon in a container like div. Perhaps it could be an option?

**Comment by yjose** [comment]
The only way you can get an element boundary is by using a ref or `findDOM` function from `react-dom`. I think FontAwesomeIcon should supporting `ref` in the first place. 

As you mentioned you can put your icon in `span` and should work correctly.

**Comment by kagant15** [comment]
I agree with @raRaRa I would expect the trigger to accept any DOM element or react component without issue.
