### ISSUE TITLE
Component wrapped in Popup created twice

### ISSUE THREAD

**Issue by leonbrag** [yjose/reactjs-popup#129]
### Version
1.5.0

### Test Case
I have following code that creates Popup window when image is clicked with AudioCalibrator child component.
The component is instantiate twice: first time without props
Second time with props.

This seems to be a bug: component should only be create once with the props.
```
<Popup modal 
trigger = { <Image src={logo} fluid /> }							
>
{ close => (											
<div open={console.log ("div on open")/*this.doCali()*/}> 
<AudioCalibrator parentCallback = {this.doCali}></AudioCalibrator>
Running: 
<a className="close" onClick={close}>
	&times;
	</a>
       </div>	
) }
</Popup>
```
In my component I have following code:

```
componentDidMount () {
  console.log ("didmount")
  if (Object.keys (this.props).length) {
    console.log (this.props)
  }
  else   {
    console.log ("No props, don't start calibration")
  }
  
}
```
I can see that componentDidMount was called twice and first time it did not receive any properties. Second time componentDidMount  was called, correct properties were received.

### Expected Behavior

Create component only once with correct parentCallback 

### Actual Behavior

Component create twice, without props

**Comment by yjose** [comment]
Hi  @leonbrag, can you provide a codesandbox example 🙏.

**Comment by leonbrag** [comment]
I tried creating fiddle https://jsfiddle.net/nv9xkcjq/3/ but I don’t know how to execute “npm install reactjs-popup –save” in the fiddle.
Therefore predictable line “import Popup from "reactjs-popup";” in the Fiddle fails

My code similar to the fiddle, except in my code I use image as trigger, not the label

**Comment by yjose** [comment]
please use this codesandbox template https://codesandbox.io/s/n5q4zqw2n0

**Comment by leonbrag** [comment]
My apologies. It was a bug in my code (component was created outside of the popup).
Thank you very much.
I will close bug

**Comment by leonbrag** [comment]
It was user issue, there is no bug.

**Comment by leonbrag** [comment]
no bug
