### ISSUE TITLE
How to set the width of the popup?

### ISSUE THREAD

**Issue by njsys** [yjose/reactjs-popup#130]
I am unable to change the width of the <popup> using styles. It always shows the popups with some width around 400-500 px. Style is having no effect. What am i doing wrong?
Thanks

Sample code.
<popup style{{width: 100px}}
   Open={this.state.showpopup}
div>
/div>
/popup>

**Comment by yjose** [comment]
Hi @njsys, to customize popup width  you need to use `contentStyle` props : https://react-popup.elazizi.com/component-api/

**Comment by AntonOfTheWoods** [comment]
@yjose 

```
<Popup contentStyle={{ width: "250px" }} />
```
Doesn't work, which is what your above comment would suggest. The only way I managed to get it done was with a styled component

```
const StyledPopup = styled(Popup)`
  &-content[role=tooltip] {
    width: 250px;
  }
`;
```
This is not very n00b-friendly for such a simple requirement, no?
