### ISSUE TITLE
Cannot read property 'getBoundingClientRect' of undefined

### ISSUE THREAD

**Issue by teagueash** [yjose/reactjs-popup#133]
### Version
1.5

### Test Case
https://codesandbox.io/s/reactjs-popup-issue-template-bupmc

### Expected Behavior
Clicking the material design icon should produce the popup.

### Actual Behavior 
Component throws an error stating: 'Cannot read property getBoundingClientRect of undefined'

**Comment by teagueash** [comment]
When I copy the files from the npm_modules directory to a directory local to my project I also get this compilation warning: 
`
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Check the render method of `Popup`.
`

**Comment by yjose** [comment]
same #128
