### ISSUE TITLE
open={this.state.open} can't control the popup correctly.

### ISSUE THREAD

**Issue by skygdi** [yjose/reactjs-popup#134]
`<Popup modal 
		            	trigger={<button className="btn btn-custom">CHOOSE YOUR STYLE</button>} 
		            	open={this.state.open} 
		            	lockScroll={true}>`

**Comment by yjose** [comment]
Hi @skygdi can you provide a complete demo using codesandbox template

**Comment by sowmika148** [comment]
I have similar question, Though we click on the button can we stop the popup being displayed by some other props?

**Comment by yjose** [comment]
you can use `disabled` prop

**Comment by yjose** [comment]
you can check the code example for controlled popup https://react-popup.elazizi.com/controlled-popup/
