### ISSUE TITLE
Warning: Stateless function components cannot be given refs

### ISSUE THREAD

**Issue by arikuza** [yjose/reactjs-popup#137]
Trigger cannot be a stateless function component, fixed wrapping by <div>

### Version
1.5.0

### Test Case
https://codesandbox.io/embed/reactjs-popup-issue-template-not5i

### Expected Behavior
no warns

### Actual Behavior
Warning: Stateless function components cannot be given refs. Attempts to access this ref will fail.

**Comment by yjose** [comment]
Hi @arikuza, 
Starting from v 1.5.0  you need to forward ref manually to make sure strict mode would work correctly.
That's mean you need to use React.forwardRef to implement your trigger component:  
```jsx
// Works
  <Popup
    trigger={open => (
      <button className="button">Trigger - {open ? "Opened" : "Closed"}</button>
    )}
    position="right center"
    closeOnDocumentClick
  >
    <span> Popup content </span>
  </Popup>
// works too
const CustomButton = React.forwardRef(({open , ...props}, ref) => (
  <button className="button" ref={ref} {...props}>
    Trigger - {props.open ? 'Opened' : 'Closed'}
  </button>
));
<Popup
    trigger={open => <CustomButton  open={open}/>}
    position="right center"
    closeOnDocumentClick
  >
    <span> Popup content </span>
</Popup> 
```

**Comment by deg** [comment]
I have a component that wraps Popup and, in turn, receives `trigger` from its users. Some of its callers passed function components, so I had this problem sometimes.

I was able to fix it with
```
    let WrappedTrigger = null;
    if (typeof trigger === "object" && typeof trigger.type === "function") {
      WrappedTrigger = trigger && React.forwardRef((props, ref)=>(
        <span {...props} ref={ref}>{trigger}</span>));
    }
...
  <Popup
...
    trigger={WrappedTrigger? <WrappedTrigger/> : trigger}   
```

I suspect/hope you can do a similar check inside Popup to fix this issue automatically for all users.
