### ISSUE TITLE
Conditional rendering

### ISSUE THREAD

**Issue by javenkn** [yjose/reactjs-popup#14]
When using a conditional render block inside `<Popup>`, it shows this warning:

```Warning: Failed prop type: Invalid prop `children` supplied to `Popup`.```

Ex. Code:
```
<Popup>
   {conditional ? <div /> : <span />}
</Popup>
```

**Comment by yjose** [comment]
Hi @javenkn, I can't reproduce the warning. I test it in my own project with Conditional rendering and it works without  warning

**Comment by Abooddy** [comment]
I'm having the same issue.

**Comment by yjose** [comment]
@Abooddy can you make sure you have the latest version 
you can found a working example here https://codesandbox.io/s/km32p367v5

**Comment by Abooddy** [comment]
I'm already using version 1.3.2. I tried wrapping it in <React.Fragment> and in a <div> and both didn't work.

**Comment by yjose** [comment]
Can you provide your  example using the codesandbox example

**Comment by jeremym** [comment]
@yjose -- I was able to re-create this error by simply making the children be two sibling divs.

A pretty quick fix would be to change your propTypes validation for children from 
`children: PropTypes.oneOfType([
      PropTypes.func,
      PropTypes.element,
      PropTypes.string,
    ]).isRequired,`
to
`PropTypes.node.isRequired`

which would also cover the `list of nodes` use case.

**Comment by yjose** [comment]
@jeremym can you send a new PR with your suggestion?

**Comment by jeremym** [comment]
Sorry Captain.  I don't have any time at the moment. :-) 

To test the issue, simply have two sibling divs.
`<Popup><div /> <div /></Popup>`
The error will go away by changing this line:
https://github.com/yjose/reactjs-popup/blob/661d87f32630cc2029f7d5affe1531bef6d77f86/src/index.js#L392 

Change the line to `PropTypes.node.isRequired` (or whatever the react library is doing now for their defaultProps; it used to be `any` as I recall, but I THINK `node` is preferred).

Thanks for the library!
Have a great weekend!
