### ISSUE TITLE
onClick of child is ignored

### ISSUE THREAD

**Issue by Ploppz** [yjose/reactjs-popup#144]
I have this code:

```
                <Popup
                    onClose={() => this.setState({selected_job: null})}
                    closeOnDocumentClick
                    trigger={
                        <IconButton size="small" onClick={this.selectJob.bind(this)} >
                            <AssignmentIcon />
                        </IconButton>
                        }
                    >
                    <div>
                        {this.state.selected_job &&
                            <>
                                <h3>Info</h3>
                                <JobInfo job={this.state.selected_job} />
                            </>
                        ||
                            <span>Loading..</span>
                    }
                    </div>
                </Popup>
```

Clicking the `IconButton` calls `this.selectJob`, which fetches a resource from a server and updates `this.state.selected_job` with the data it got from the server.

With how it currently works, the above code does not work because `Popup` seems to ignore or override the `onClick` of its child.
I did however manage to work around this by putting the `onClick` on the `AssignmenIcon` instead, so it seems like the problem only applies to immediate children of `Popup`.

**Comment by yjose** [comment]
Hi Ploppz , thank you for your remark.
Can you  please provide a working code sandbox with you issue using code sandbox template   https://codesandbox.io/s/n5q4zqw2n0

**Comment by Ploppz** [comment]
https://codesandbox.io/s/reactjs-popup-issue-template-mtd0k

**Comment by Ianohurr** [comment]
@yjose Did anything every happen with this? I'm having a similar issue trying to run an error check before the modal opens, but onClick does nothing when the button is set to the trigger.

**Comment by yjose** [comment]
@Ploppz  @Ianohurr  using `onOpen` should work in such case   https://codesandbox.io/s/reactjs-popup-issue-template-g92tr
