### ISSUE TITLE
Feature: allow render content into a portal

### ISSUE THREAD

**Issue by zhaoyao91** [yjose/reactjs-popup#159]
Currently it place the content box just next to the trigger element. If the trigger element is inside a container which has style `overflow: hidden` or `overflow: auto`, the popup cannot really popup outside of it and thus being hidden.

In other popup/tooltip solutions, they render content in the body, which make sure the popup always get rendered. If reactjs-popup allow us to render the content inside custom portal, that would be nice to solve such problems

**Comment by d-pollard** [comment]
yeah, this is a really painful sticking point

**Comment by lainermeister** [comment]
Does anyone know of a good library that portals popup content? 

We were using semantic-ui's but once you have a nested sub-menu, `onClick` functions do not get registered in the 2nd layer of the popup - getting overridden by the pop-up change handlers.

I would love to give this library a try, but also need the portaling feature.

**Comment by yjose** [comment]
@zakariaelas  @lainermeister  Portal is coming with v2

**Comment by zhaoyao91** [comment]
@yjose do you know when v2 will be released?

**Comment by vzaidman** [comment]
Portal is coming with v2! Wow!
Can i help somehow with releaseing it? any PR or something?

**Comment by yjose** [comment]
v2 is here : https://github.com/yjose/reactjs-popup/releases/tag/v2.0.0

**Comment by Slapbox** [comment]
@yjose can you explain how to use the portal feature? Or is it always on? I searched the entirety of the docs for the word "portal" but didn't find any mention.
