### ISSUE TITLE
Open Modal when ComponentDidMount

### ISSUE THREAD

**Issue by rahmatkruniawan** [yjose/reactjs-popup#16]
**How to Open dialog modal when component called  ??**

**Comment by yjose** [comment]
Hi @rahmatkruniawan ,
The reactjs-popup support controlled way  and uncontrolled way,
In your case, you need to take a look at this example on the reactjs-popup homepage : 
https://react-popup.netlify.com/controlled-popup/  
So if you want to open the popup in ComponentDidMount lifecycle you just need to call the openModal function inside ComponentDidMount.

have a nice day
