### ISSUE TITLE
popup is not closing which is inside the array list in each item

### ISSUE THREAD

**Issue by cullsin** [yjose/reactjs-popup#162]
I have a popup dialog inside an array list and each item has it is own popup dialog option. It is working fine and when I try to close the popup modal it is not closing it up.

        [
                     <Popup
                        closeOnDocumentClick
                        open={this.state.isModalCommentOpen}
                        onClick={() =>
                          this.openModalComment(comments.owncomments)
                        }
                        trigger={<span className=''>Edit Comment</span>}
                        position='center'>
                        <SampleComponent
                          handleCloseModalComment={this.handleCloseModalComment}
                          
                        />
                      </Popup>,
                     <Popup
                         closeOnDocumentClick
                        open={this.state.isModalCommentOpen}
                        onClick={() =>
                          this.openModalComment(comments.owncomments)
                        }
                        trigger={<span className=''>Edit Comment</span>}
                        position='center'>
                        <SampleComponent
                          handleCloseModalComment={this.handleCloseModalComment}
                        />
                      </Popup> 
          ]

### Version
npm default version

### Test Case
https://codesandbox.io/s/reactjs-popup-issue-template-dv61j

### Expected Behavior
popup should close.

### Actual Behavior
popup is not closing.

**Comment by yjose** [comment]
need to remove the `open` prop  to make sure the Popup in unControlled

**Comment by cullsin** [comment]
Hello, 

If  that is the case, how do I close the popup after successful transaction inside the popup ? 

https://codesandbox.io/s/reactjs-popup-issue-template-dv61j

Thanks.

**Comment by yjose** [comment]
Use render prop pattern to close the popup whenever you want 
https://codesandbox.io/s/reactjs-popup-issue-template-8yoji
