### ISSUE TITLE
Gatsbyjs doesn't hot load when implementing Popup

### ISSUE THREAD

**Issue by famlyman** [yjose/reactjs-popup#17]
### Version
1.1.0

### Test Case
https://codesandbox.io/s/n5q4zqw2n0

### Expected Behavior
Popup modal in Gatsbyjs app.
### Actual Behavior
After saving hot reload in localhost shows blank screen until I delete Popup from app.

**Comment by yjose** [comment]
look like this problem related to gatspyjs project https://github.com/gatsbyjs/gatsby/issues/5534

**Comment by famlyman** [comment]
Thank you very much.

**Comment by yjose** [comment]
Hi @famlyman 

As you see in the Reactjs-popup readme the component  requires React >= 16.0 and Gatsby v1 is using React 15

You can use gatsby-plugin-react-next to use React 16 with v1 and hopefully that will sort things out!

Please reopen the issue if the problem persists 🙂

**Comment by famlyman** [comment]
Oh sweet, I missed that. Thank you again for all you do.

**Comment by famlyman** [comment]
I updated Gatsby to React 16 per your instructions and the problem persists. Attached is the screenshot of the React version for confirmation. As well as the version of Reactjs Popup.
![screenshot_2](https://user-images.githubusercontent.com/13388878/40580815-26579208-6115-11e8-8785-014719fff095.png)

![screenshot_1](https://user-images.githubusercontent.com/13388878/40580798-eabb61b6-6114-11e8-9825-d8117f65a495.png)

**Comment by yjose** [comment]
You cant update gatspy to react 16 it will not work. As you see i suggest that you use the gatspy plug-in react next

**Comment by famlyman** [comment]
Correct, I updated per your instructions on the previous email.
