### ISSUE TITLE
Do not close modal on mouseup outside the modal but on click

### ISSUE THREAD

**Issue by josdejong** [yjose/reactjs-popup#174]
Thanks for sharing this library, it works like a charm :+1: .

We came across a small issue: when selecting text in a popup and having mouse-up event occur outside of the popup, the popup is closed. It would be nice if this would not close the popup, and the popup is only closed when really clicking outside (mouse down and mouse up outside). Would that be possible?

To reproduce: 

- Open https://react-popup.elazizi.com/home/
- Open the demo popup by clicking the button "Open modal"
- Select all text inside the popup, and make sure that your mouse is _outside_ of the popup when you let the pressed mouse button go. 
- Now, the popup closes, whilst I would like it to stay open.

**Comment by josdejong** [comment]
For anyone with the same issue, I created the following workaround:

```ts
// filename: useCloseOnDocumentClick.ts
import { useEffect, useState } from 'react'

/**
 * This hook is a workaround for an issue in reactjs-popup
 *
 * What this hook does is:
 *
 * - on mouse down inside the popup, set closeOnDocumentClick to false
 * - on mouse up, set closeOnDocumentClick to true
 *
 * Usage:
 *
 *    const closeOnDocumentClick = useCloseOnDocumentClick()
 *
 *    return (
 *      <Popup ... closeOnDocumentClick={closeOnDocumentClick} >
 *        ...
 *      </Popup>
 *    )
 */
export default function useCloseOnDocumentClick () {
  const [closeOnDocumentClick, setCloseOnDocumentClick] = useState(true)

  useEffect(() => {
    function insidePopupContents(target: any) : boolean {
      return target.querySelector('.popup-content') == null
    }

    function handleMouseDown (event: MouseEvent) {
      if (insidePopupContents(event.target)) {
        setCloseOnDocumentClick(false)
      }
    }

    function handleMouseUp () {
      setTimeout(() => setCloseOnDocumentClick(true))
    }

    window.document.addEventListener('mousedown', handleMouseDown)
    window.document.addEventListener('mouseup', handleMouseUp)

    return () => {
      window.document.removeEventListener('mousedown', handleMouseDown)
      window.document.removeEventListener('mouseup', handleMouseUp)
    }
  }, [setCloseOnDocumentClick])

  return closeOnDocumentClick
}
```

Not ideal but it does the job.

**Comment by yjose** [comment]
fixed v2

**Comment by josdejong** [comment]
Thanks for the fix Youssouf 👍 ! I can confirm it works like a charm now.

**Comment by Crustan** [comment]
Is this issue really fixed? We just discovered the same issue in v 2.0.4. And if you follow the steps to reproduce in the first comment, you still get the same issue.
