### ISSUE TITLE
passing className to Popup component doesn't do anything

### ISSUE THREAD

**Issue by Eliav2** [yjose/reactjs-popup#178]
### Test Case
https://codesandbox.io/s/reactjs-popup-issue-css-u137s?file=/src/index.js

### Expected Behavior
assigning css properties on popup menu with `className` WORK as it works when giving Popup component styling using `contentStyle` with just jsx.
 
### Actual Behavior
assigning css properties on popup menu with `className` DOES NOT WORK as it works when giving Popup component styling using `contentStyle` with just jsx.

tried also using `.popup-overlay` and `.popup-content` as the docs suggested but not working also.
also inspected the dom to see what classes you finally give the mounted component and found that if for example i passed `className="ssss"` then the Popup component will receive `ssss-content` so i also tried define `ssss-content` but  the properties i passed  is over-written with `element.style`
![image](https://user-images.githubusercontent.com/47307889/82848342-c0fce300-9efb-11ea-8078-5b73d23df0dd.png)

what if i want to use your component with the use of css without the use of `styled-component` or passing style to `contentStyle`?
(note -  i did not defined width of 200px anywhere but yet your styling is overwritten my css width property to be 200px)

**Comment by yjose** [comment]
hey @Eliav2, tyou cant override inline style using className, to override default styling such as `width` you need to use `contentStyle `.

**Comment by Eliav2** [comment]
You should apply default styling to your component in css so it will not override user css inline styling.
