### ISSUE TITLE
Modal window is cut off on small sizes

### ISSUE THREAD

**Issue by ArtemiusL** [yjose/reactjs-popup#18]
Thank you for library!
When i do screen small then modal window is cut off, i will want that to can be use this library on mobile devices.
It will be cool if the small screen sizes will `overflow-y: scroll or auto` like fancybox in JQuery.
http://prntscr.com/js0lmw

**Comment by yjose** [comment]
Hi, @ArtemiusL ,
Thanks for your remarks,
I think you just need to custom container modal using contentStyle prop. 
Please provide me your snippet so I can help you !!!
