### ISSUE TITLE
popup with arrow breaks the arrow when i forcly open the popup

### ISSUE THREAD

**Issue by vtarelkin** [yjose/reactjs-popup#181]
I have a popup in my react-table's header

```
    const column = [{
        Header: () =>
            <div>
                <Popup className="column-order-popup"
                       closeOnDocumentClick
                       open={wasPopupOpen}
                       repositionOnResize
                       trigger={<div className="eye-icon">
                           <img src={icon}/>
                       </div>}
                       on="click"
                       position="bottom left">
                    <div className="column">
                        {generate()}
                    </div>
                </Popup>
            </div>,
        fixed: "left",
        sortable: false,
        headerClassName: "table-header-class",
        className: "table-row-class",
        width: 70
    }];


    const generate = () => {
        return (
                            <div className="checkbox-react-table">
                                <img onClick={(e) => handleToggleShowColumnClick()} alt="image"
                                     src={checkboxMarked}/>
                            </div>
        )
    };

    const handleToggleShowColumnClick = () => {
...
        setWasPopupOpen(false);
        setWasPopupOpen(true);
    };
```
I have checkbox inside the popup which sets the visibility of the column, so it re-draws the table.
After I'm clicking on the checkbox the popup closes. I don't like such behavior and I set wasPopupOpen to true. After that popup stays opened but arrow breaks. If I set arrow to false it looks ok, but I like arrow))) Also I noticed that the popup after setting open to true moves a bit to another position. When I set render on resize and resize the window - it looks ok. Maybe I can call resize somehow? 

before
![image](https://user-images.githubusercontent.com/46703134/84953579-733f5900-b0fc-11ea-9f34-d97e48916fe4.png)

after
![image](https://user-images.githubusercontent.com/46703134/84953718-b0a3e680-b0fc-11ea-9c13-aa9d99fecf62.png)

**Comment by yjose** [comment]
Hey @vtarelkin , can you provide a codesandbox example to see if I can help on this 👍
