### ISSUE TITLE
is it possible to place popup code in one place and trigger in another?

### ISSUE THREAD

**Issue by vtarelkin** [yjose/reactjs-popup#182]
When I put popup in my react-table (popup is triggered after I click on  header of the first column) it is re-rendering and popup dissapears. I want to re-render the table, let the trigger to be on the header but put code out of the table, so popup shouldn't dissapear.

Is it possible? Maybe refs?

**Comment by yjose** [comment]
Hey @vtarelkin , can you provide a codesandbox example to see if I can help on this 👍

**Comment by vtarelkin** [comment]
@yjose good question.
it doesn't allow me to create a sanbox, please consider very simple example from your
https://codesandbox.io/s/k9k36x70kv?file=/src/examples/InputFocus.js:262-326 
- I just put the input out of the trigger, but I still want the popup to be triggered by input  BUT I don't want the input to be rendered INSIDE the <Popup>
```

import React, { useRef }  from "react";
import Warper from "./Warper";
import Popup from "reactjs-popup";
//
const refToInput  = useRef(null);
const InputFocus = () => (
<div>
  <Popup
    trigger={ref}
    on="focus"
    position="top center"
    closeOnDocumentClick
  >
    <span> On focus popup event </span>
  </Popup>
  <input ref={refToInput} type="text" placeholder="start typing ... " />
  </div>
);

export default Warper(InputFocus);

```

**Comment by vtarelkin** [comment]
@yjose BTW There is another approach. I don't want to use open={state_param} option in popup, because it want uncontrolled popup with arrow and position in exact place. I want to avoid open parameter in popup and I want to set the trigger on header's element but outside of the react-table code.

**Comment by yjose** [comment]
@vtarelkin  change `trigger={refToInput.current}` by `ref={refToInput}` and you ref should have access to  Native Components functions   such us `openPopup`
check this example : https://github.com/DevC-Casa/geeksblabla.com/blob/master/src/components/Suggest/auth0.js

**Comment by vtarelkin** [comment]
@yjose thank you for your answer.

Yes, I used `ref` in popup. And in onClick() of the element I did  `onClick={() => popupRef.current.openPopup()`

It worked, but: the popup appears in random place. Yes, I can put it in right place with margins and padding, tops and lefts, but I still want to use position option, but unfortunately popup doesn't take it. Also I want to have stylish arrow but it doesn't work.

**Comment by yjose** [comment]
If you are using popup you should add trigger element, you can create an empty div and set the position you want or you can use Modal, 
To style arrow, you can use 'arrowStyle'   property

**Comment by vtarelkin** [comment]
@yjose any example, please? I cannot understand how I can handle this with empty div

**Comment by vtarelkin** [comment]
if anyone will be there

I just did an empty div and put trigger in it

```
        trigger={<div className="sample-trigger"></div>}

.sample-trigger {
    width: 1px;
    height: 1px;
    display: block;
    visibility: hidden;
}
```
In the main div I am using to trigger the popup I set the onClick to change the state of {wasPopupOpen}
```

   <Popup
        className="popup"
        closeOnDocumentClick
        open={wasEyePopupOpen}...
```
I also make some adjustmenst on popup window so it looks like inside of that div.
