### ISSUE TITLE
closeOnDocumentClick does not close already opened popup

### ISSUE THREAD

**Issue by sergeyt** [yjose/reactjs-popup#183]
### Version
1.5.0

### Test Case
https://codesandbox.io/s/reactjs-popup-issue-template-uxs0i?file=/src/index.js

### Expected Behavior
When using `closeOnDocumentClick` Popup must close previously opened Popup and open new one.

### Actual Behavior
1. Click on First. See fist popup
2. Click Second. See two popups shown

**Comment by erisnuts** [comment]
I fixed this with react-onclickoutside.
Wrapper:
`import React from 'react';
import onClickOutside from 'react-onclickoutside';

interface IContentWrapper {
  children: JSX.Element;
  onClickOutside: () => void;
}

class OnClickOutsideWrapper extends React.Component<IContentWrapper> {
  handleClickOutside = () => {
    setTimeout(this.props.onClickOutside, 200);
  };

  render() {
    return <>{this.props.children}</>;
  }
}

export default onClickOutside(OnClickOutsideWrapper, {
  excludeScrollbar: true,
});`

Usage:
`const InfoButton: React.FC<IActionButton> = ({ id }) => {
  const [open, setOpen] = React.useState(false);

  const handleOpen = () => {
    setOpen(true);
  };

  const handleClose = () => {
    setOpen(false);
  };

  return (
    <Popup
      open={open}
      className='deleted-rules__tooltip'
      trigger={
        <button onClick={handleOpen} className='icon-button'>
          <InfoIcon />
        </button>
      }
      position='left center'
    >
      <OnClickOutsideWrapper onClickOutside={handleClose}>
        <DeletedRuleDetails id={id} />
      </OnClickOutsideWrapper>
    </Popup>
  );
};`

**Comment by erisnuts** [comment]
I fixed this with react-onclickoutside

**Comment by yjose** [comment]
fixed with v2 : https://codesandbox.io/s/reactjs-popup-issue-template-forked-bs3vd?file=/src/index.js
