### ISSUE TITLE
Feature proposal: Render tooltip popup programmatically

### ISSUE THREAD

**Issue by virtumonde** [yjose/reactjs-popup#185]
One very useful feature would be rendering the tooltip popup programmatically. Right now as I understand you can trigger it only using a button:

```
    <Popup
      trigger={<button className="button"> Right Top </button>}
      position="right top"
      on="hover"
    >
```

My proposal is to give the user the ability to trigger the display using a function:

```
    <Popup
      display={() => // return true to display the popup and false otherwise}
      position="right top"
      on="hover"
    >
```

**Comment by vtarelkin** [comment]
@virtumonde there is an ` open={true} `param you can use)

**Comment by yjose** [comment]
you can use  `open` prop and use the component as a controlled popup, but also you can access to popup internal functions such us `openPopup` using refs. 

```
const ref = creatRef() 
<Popup
      trigger={<button className="button"> Right Top </button>}
      position="right top"
      on="hover"
      ref={ref}
    >
```
and you can use ref to call popup functions 
```
ref.current.openPopup(); 
ref.current.closePopup(); 
```
