### ISSUE TITLE
Trigger Popup from code

### ISSUE THREAD

**Issue by eliranbenishai** [yjose/reactjs-popup#19]
Unless I missed something, the only way to trigger a popup is by providing a DOM element for the trigger property. I would like the popup to be triggered by certain events (like server responses) that do not correspond to elements in the dom. Would that be possible?

Thanks!

**Comment by yjose** [comment]
Hi @eliranbenishai , thanks for your remark, reactjs-popup can't do this out of the box.but it simple I think:
* first Approach: you just need to use the popup component As a controlled component ( [example here](http://react-popup.netlify.com/controlled-popup/)  ) and update the popup state everywhere and after server response.
* 2nd Approach : (the best and more generic) I think you can simply make it possible by creating A popup component Provider using  the new context API from react (16.3 >) and you can trigger  everywhere using the Context Consumer 

lets me know if it works for you or you have any problem implementing those approaches.
