### ISSUE TITLE
Could not get this to work for my purposes. Does not work inside child components, only a root component. Docs not helpful.

### ISSUE THREAD

**Issue by Danscap** [yjose/reactjs-popup#190]
I have the navigation menu below.

![image](https://user-images.githubusercontent.com/34867523/87726915-ef759c80-c78d-11ea-878c-25f076988ce4.png)

This is the code I am trying to use:

![image](https://user-images.githubusercontent.com/34867523/87727068-40859080-c78e-11ea-94ad-5a25f34fd64d.png)

![image](https://user-images.githubusercontent.com/34867523/87727191-7fb3e180-c78e-11ea-870e-70e6125576fd.png)
It is called later like the above.

I could only get the tooltips to work if the component is directly on the page and does not have a parent. As for the above, the tooltip cannot be summoned no matter what 'on' event. I'm not sure what to do at this point.

**Comment by yjose** [comment]
should be fixed with v2 as we start using portals

**Comment by Nazar-cmd** [comment]
As a temporary decision you can wrap your component with div or any other tag, but not with <> or <React.Fragment>. Because with using latter there will be no error, but popup won't be showing
` 
<Popup
                trigger = {<div> <Combobox/> </div>}
                position="top center"
                on="hover"
            >
                <span> {error} </span>
</Popup>
`

**Comment by yjose** [comment]
Just pushed a new pre-release 2.0.0-0, can you please make sure it's working correctly for your use case
