### ISSUE TITLE
Display different between desktop and iOS

### ISSUE THREAD

**Issue by Sislar** [yjose/reactjs-popup#192]
My app had main div that covers the View port, this has a child div that slides out from the side as a control panel there are
several controls that work fine however two buttons are popups.  On the desktop when I click either I get the model dialog as expected that is centered in the viewport. However when this same page is on iOS (ipad or iPhone) then the popup is "within" the smaller div and is only a small part is visible. This is a controlled dialog. I've tried it on different browsers and it doen't chnage by browser.

### Expected Behavior
Dialog is centered in the viewport, behavior on desktop and iOS should be the same.

### Actual Behavior
iOS dialog is within the child div and is clipped to the divs boundaries.

                          <Popup trigger={<button className="gtCpButton"> Remove Player </button>} modal>
                              {close => (
                                <div className="modal">
                                  <div className="content">
                                      <p>As Table Owner you can remove players, they can rejoin if the table is still public</p> 

                                      <div className="gtKickmeRow">
                                        <span>Select a player remove</span>     
                                        <select id="gtKickme">
                                        {this.state.seatingData.map((seat)=>{
                                          if (seat.playerid !== this.props.PlayerId)
                                            return(<option key={seat.playerid} value={seat.playerid}>{seat.displayname}</option>)
                                          return null;
                                          }) 
                                        }
                                      </select>
                                    </div>

                                  </div>
                                  <div className="ConfirmButtons">
                                    <button onClick={() => {this.removePlayer(); close();}} >Kick Player </button>
                                    <button onClick={() => {close();}} > Cancel </button>
                                  </div>
                                </div>
                              )}
                            </Popup>

**Comment by yjose** [comment]
hey @Sislar , can you please provide a codesandbox project  for your use case

**Comment by Sislar** [comment]
I finally track it down and it wasn't the popup code.

I had Overflow:auto and it behaves differently in the Ios Chrome  vs
desktop Chrome.  So was a Css issue or
maybe a chrome bug as I don't know why it should be different.

**Comment by yjose** [comment]
Great, I think we need to close this issue  😄
