### ISSUE TITLE
Styling with styled components when arrow={true}

### ISSUE THREAD

**Issue by net-bet** [yjose/reactjs-popup#198]
### Version
latest

### Test Case
https://codesandbox.io/s/reactjs-popup-issue-template-forked-qrmxv?file=/src/index.js

### Expected Behavior
Styling works?

### Actual Behavior
Error when I trigger the popup:
Failed to execute 'add' on 'DOMTokenList': The token provided ('sc-AxjAm eiefsA-arrow') contains HTML space characters, which are not valid in tokens.

In general, all I want is the ability to style the triggered element. I can do it, but in order to style the arrow I must have a way to style it. I don't want to use global css. Is it possible?

**Comment by yjose** [comment]
for now, you can only style the popup arrow using className (global CSS) or using `ArrowStyle` prop(inline CSS )

**Comment by net-bet** [comment]
I think the arrowStyle can work great for me, where can I find a documentation/example how to set it up

**Comment by yjose** [comment]
@net-bet check the component API page https://react-popup.elazizi.com/component-api/  maybe you can get some inspiration from  initial styling => https://github.com/yjose/reactjs-popup/blob/master/src/index.css.js#L21

**Comment by net-bet** [comment]
awseome! exactly what I needed
