### ISSUE TITLE
Feature Request: Documented sample app including popup

### ISSUE THREAD

**Issue by dalepres** [yjose/reactjs-popup#199]
I know it seems trivial but as a developer new to react, it would be helpful to see not just the documented ways to trigger and create popups but to also see how it fits into an existing app.  For instance, I have an app with a parent component that contains a collection of components.  How and where would I insert the popup code to make my app work until the trigger is executed?

**Comment by yjose** [comment]
the  popup implementation should work on every react project, try to copy-paste one of the [examples](https://react-popup.elazizi.com/), should work correctly
