### ISSUE TITLE
Multiple popups open-close issue

### ISSUE THREAD

**Issue by amitpatel9169** [yjose/reactjs-popup#200]
In my case, I have 3 popups on one page.

assume that I have 2 popups and
trigger1 popup is open and click on trigger2 popup button then I want to open trigger2 popup and trigger1 popup closed

code sandbox demo:- 
[https://codesandbox.io/s/pedantic-haibt-p1m32](                                https://codesandbox.io/s/pedantic-haibt-p1m32)

image of the multiple popups:-
                               [https://prnt.sc/u7vckw](https://prnt.sc/u7vckw)
Please help

**Comment by yjose** [comment]
Hey @amitpatel9169 , i am planning to release v2 tomorrow, for sure will fix your issue

**Comment by amitpatel9169** [comment]
@yjose thanks for the reply. I am waiting for v2

**Comment by yjose** [comment]
@amitpatel9169  just pushed a new prerelease with the fix 
https://codesandbox.io/s/runtime-rgb-fdj2v?file=/src/App.js

**Comment by amitpatel9169** [comment]
@yjose Thanks, my issue is resolved using an updated version

**Comment by amitpatel9169** [comment]
@yjose issue is resolved but my custom popup and model design is totally changed in the new update installation.

so, any solution for the design issue by your end?

**Comment by yjose** [comment]
Make sure to import default css from package, 
Import 'reactjs-popup/dist/index.css'

**Comment by amitpatel9169** [comment]
@yjose Something is missing in your new version uploaded

check once because import CSS statement not working it gives the error

error:- Module not found: Can't resolve 'reactjs-popup/dist/index.css'

and package reactjs-popup@2.0.0-1 is already on my project

**Comment by yjose** [comment]
@amitpatel9169 , can you please tell me exactly how the design has been changed? 
for now, forgot about Import 'reactjs-popup/dist/index.css' as it will be the default  in the next version

**Comment by amitpatel9169** [comment]
@yjose no problem. the design issue is not a big deal for me I will handle it by my side. 

thanks for the support

**Comment by amitpatel9169** [comment]
hey @yjose please look at the below codesendbox demo

link:- [https://codesandbox.io/s/hardcore-clarke-k6wq4](https://codesandbox.io/s/hardcore-clarke-k6wq4)

In this demo one popup and in the popup one model

on a button, click open the popup, and after a click on the open model button  model is open perfectly but 
even I clicked on the model inside content then close the model and popup both

if I am not wrong then on model inside the content click model is not close in your older version 

so please can you help me

**Comment by yjose** [comment]
Starting from v2 You need to set nested prop to true https://react-popup.elazizi.com/migrate-from-v1-to-v2
