### ISSUE TITLE
Incorrect lockScroll behaviour on controlled modals

### ISSUE THREAD

**Issue by csalgau** [yjose/reactjs-popup#202]
In v2 lockScrolll() and resetScroll() are only called on uncontrolled behaviour for Popups.
The useEffect hook only toggles the `open` state. 

### Version
2.0.1

### Test Case
https://codesandbox.io/s/reactjs-popup-issue-template-forked-jh2bd

### Expected Behavior
`overflow: hidden;` set on body on open
`overflow: auto;` set on body on close

### Actual Behavior
no style set on body on open
`overflow: auto;` set on body on close if closing by uncontrolled methods
no style set on body on close if setting open to false in a controlled manner (not shown in test)

**Comment by yjose** [comment]
nice catch @csalgau , woking on a fix ....

**Comment by yjose** [comment]
the fix didn't work with the default open popup, will be fixed ASAP

**Comment by yjose** [comment]
fixed => https://codesandbox.io/s/reactjs-popup-issue-template-forked-z0j2n?file=/src/index.js
