### ISSUE TITLE
Get the console error

### ISSUE THREAD

**Issue by amitpatel9169** [yjose/reactjs-popup#209]
I don't know why but in my project show the below error in console. 

e.current.contains is not a function

![image](https://user-images.githubusercontent.com/54776777/93581987-7a0d8e80-f9bf-11ea-9e4d-0b1a44d01b78.png)

Can anyone help me to remove this error

**Comment by yjose** [comment]
@amitpatel9169 can you please provide  a codeSandbox  for your issue 🙏

**Comment by amitpatel9169** [comment]
@yjose sorry my bad 
Issue is resolved I directly use the link(a tag) in trigger popup open-close that's why console error is coming

like this,
> <Popup trigger={(open) => <a> Trigger 1 </a>}>
        {(close) => (
          <div>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores
            dolor nulla animi, natus velit assumenda deserunt molestias
          </div>
        )}
      </Popup>


after adding div and then give link it's working without any console error

**Comment by alabeduarte** [comment]
Hi @amitpatel9169 

I'm facing a similar issue that is only happening on Safari. You mentioned that you solved your issue by adding a `div` within the `trigger`. Would you happen to have or remember the code snippet with your final solution?

It was something like the code below?

```javascript
<Popup trigger={(open) => <div>Trigger 1</div> }>
```

Cheers

**Comment by alabeduarte** [comment]
I think I've got it. I was having similar issue and I got it working when I made sure that whatever is rendered within `trigger` will be wrapped by any valid DOM tag (i.e. `div`, `span`, etc).

Cheers
