### ISSUE TITLE
Show modal in the other subtab

### ISSUE THREAD

**Issue by yun-li** [yjose/reactjs-popup#21]
Hello,

I have a webpage containing several subsections under the same url, such as 

  _____________________________________________________________________________
   **nav area:**                        subsection1  |  subsection2  |  subsection 3
  _________________________________________________________________________________

   **body:**                 Contents for subsection 1 or 2 or 3 depending on the section selected.

  _________________________________________________________________________________

Under any subsection, if I start the popup, it always shows under the first subsection, that is to say, I have to click the first subsection to see the popup when I start the popup in the 2nd or 3rd subsection, is this a bug or am I did something wrong?

Thanks very much,
Yun

**Comment by yjose** [comment]
Hi @yun-li ,
look like you have a css issue here , can you provide me an example using the sandbox issue template here https://codesandbox.io/s/n5q4zqw2n0
thanks
