### ISSUE TITLE
In next 9.5.3, "Converting circular structure to JSON" error came.

### ISSUE THREAD

**Issue by nitishkrs1987** [yjose/reactjs-popup#213]
### Version
Next JS - 9.5.3
React - 16.12.0

### Expected Behavior
Without any exception
### Actual Behavior
Converting circular structure to JSON
    --> starting at object with constructor 'FiberNode'
    |     property 'stateNode' -> object with constructor 'DetailPage'
    --- property '_reactInternalFiber' closes the circle

**Comment by yjose** [comment]
👋 @nitishkrs1987  
Can you please provide a codesandbox demo for your use case
