### ISSUE TITLE
Issue with click outside to close the popup

### ISSUE THREAD

**Issue by josdejong** [yjose/reactjs-popup#217]
In one of the reactjs-popups we have, we open a small yes/no confirm popup _on top of_ the reactjs-popup. This confirm modal uses a different react library.

Since upgrading to `reactjs-popup@2`, clicking in this confirm modal will close the main reactjs-popup that is behind it, but that should not happen. It looks like reactjs-popup considers any click outside of it's own popup as "click outside" and will close itself. Instead, I think it should only consider a click a "click outside" when clicked on the overlay of reactjs-popup itself. Does that make sense?

I tried but didn't find a workaround, for we will switch back to `reactjs-popup@1.5.0` where this does not happen.

**Comment by yjose** [comment]
👋 @josdejong , would like it if you can provide a code sandbox for your issue use case.
Also, I would suggest adding `nested={true}` probably will fix the issue.

**Comment by josdejong** [comment]
Thanks, `nested={true}` indeed solves the issue, that's a good workaround 👍 .

I've created a code example to demonstrate the issue: https://codesandbox.io/s/reactjs-click-outside-issue-mhqrd?file=/src/App.js

**Comment by yjose** [comment]
Well, You should read the Migration Guide in the Doc website 😀
https://react-popup.elazizi.com/migrate-from-v1-to-v2#nested-popup

**Comment by josdejong** [comment]
Yes you're right. To be honest, I totally didn't expect this behavior to be a new _feature_...

This makes me really curious: what is the use case for `nested={false}`? I cannot think of a case but I suppose I'm missing something.

**Comment by yjose** [comment]
we faced some issues with the old implementation #200 #197 #184  due to supporting nested Popup. 
To fix those issues we came up with the decision to add a `nested` prop to make sure the behavior will work for both cases.

**Comment by josdejong** [comment]
Thanks for the explanation Youssouf 👍 . Too bad that it's not possible to have a single solution that works for all the use cases!
