### ISSUE TITLE
Feature request: change structure

### ISSUE THREAD

**Issue by pycckuu** [yjose/reactjs-popup#225]
First of all, I would like to say that it is a great piece of work! I really enjoy using it in my projects.

For me, the structure of the `Popop` component will be more logical if we change the _child_ component with `trigger`, i.e., instead of writing: 

```js
export default () => (
  <Popup trigger={<button> Trigger</button>} position="right center">
    <div>Popup content here !!</div>
  </Popup>
);
```

Use: 
```js
export default () => (
  <Popup trigger={<div>Popup content here !!</div>} position="right center">
	<button> Trigger</button>
  </Popup>
);
```

And rename `trigger` to `popupContent` or something else. 

Is it possible?

**Comment by yjose** [comment]
thanks, @pycckuu  for your contribution, I am not sure if your proposal is the best option in our case, changing the API for component comes with complicity to support the old version and I would see that having the popup content as a child has more sense than having the trigger as a child. That's I wouldn't recommend changing the component API.
