### ISSUE TITLE
npm install reactjs-popup --save failed to install

### ISSUE THREAD

**Issue by besiwims** [yjose/reactjs-popup#226]
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\Tobb>cd nexchange-open-client-react

C:\Users\Tobb\nexchange-open-client-react>npm install reactjs-popup --save

> scrypt@6.0.3 preinstall C:\Users\Tobb\nexchange-open-client-react\node_modules
\scrypt
> node node-scrypt-preinstall.js

> scrypt@6.0.3 install C:\Users\Tobb\nexchange-open-client-react\node_modules\sc
rypt
> node-gyp rebuild

C:\Users\Tobb\nexchange-open-client-react\node_modules\scrypt>if not defined npm
_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\np
m-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )
  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin
\node-gyp.js" rebuild )
Warning: Missing input files:
C:\Users\Tobb\nexchange-open-client-react\node_modules\scrypt\build\..\scrypt\wi
n\include\config.h
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
  Copying scrypt/win/include/config.h to scrypt/scrypt-1.2.0/config.h
  The system cannot find the file specified.
  win_delay_load_hook.cc
LINK : fatal error LNK1117: syntax error in option 'LTCG:INCREMENTAL' [C:\Users
\Tobb\nexchange-open-client-react\node_modules\scrypt\build\copied_files.vcxpro
j]
  memlimit.c
  keyderivation.c
  pickparams.c
  hash.c
  win_delay_load_hook.cc
  scrypt_wrapper.vcxproj -> C:\Users\Tobb\nexchange-open-client-react\node_modu
  les\scrypt\build\Release\\scrypt_wrapper.lib
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:248:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Tobb\nexchange-open-client-react\node_modules\scrypt
gyp ERR! node -v v10.15.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed.
 You must install peer dependencies yourself.
npm WARN eslint-config-react-app@2.1.0 requires a peer of babel-eslint@^7.2.3 bu
t none is installed. You must install peer dependencies yourself.
npm WARN nexchange-open-client-react@0.1.0 No repository field.
npm WARN nexchange-open-client-react@0.1.0 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules\sa
ne\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32
"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules\ch
okidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32
"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scrypt@6.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Tobb\AppData\Roaming\npm-cache\_logs\2020-12-05T10_51_49_6
20Z-debug.log

C:\Users\Tobb\nexchange-open-client-react>node-gyp rebuild
'node-gyp' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Tobb\nexchange-open-client-react>npm node-gyp rebuild

Usage: npm <command>

where <command> is one of:
    access, adduser, audit, bin, bugs, c, cache, ci, cit,
    completion, config, create, ddp, dedupe, deprecate,
    dist-tag, docs, doctor, edit, explore, get, help,
    help-search, hook, i, init, install, install-test, it, link,
    list, ln, login, logout, ls, outdated, owner, pack, ping,
    prefix, profile, prune, publish, rb, rebuild, repo, restart,
    root, run, run-script, s, se, search, set, shrinkwrap, star,
    stars, start, stop, t, team, test, token, tst, un,
    uninstall, unpublish, unstar, up, update, v, version, view,
    whoami

npm <command> -h  quick help on <command>
npm -l            display full usage info
npm help <term>   search for help on <term>
npm help npm      involved overview

Specify configs in the ini-formatted file:
    C:\Users\Tobb\.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@6.4.1 C:\Program Files\nodejs\node_modules\npm

C:\Users\Tobb\nexchange-open-client-react>

**Comment by yjose** [comment]
hey @besiwims, your problem is not related to the `reactjs-popup` module. 
the problem is related to `node-gyp`  which have common issues with Windows OS  https://github.com/nodejs/node-gyp/issues/809

**Comment by besiwims** [comment]
Thanks for your response. Most recommendations are deleting "~/.node-gyp folder and then the ~/.npmrc file" and restarting the machine. I will try that.
