### ISSUE TITLE
full screen availability

### ISSUE THREAD

**Issue by spinybeast** [yjose/reactjs-popup#24]
Hi! Thank you for awesome component. What if I need fullscreen modal? Is there the opportunity?

**Comment by yjose** [comment]
Hi @spinybeast , 
if you need a fullscreen modal just need to add the `contentStyle`  to the `Popup` Component as the following  Codesandbox example  https://codesandbox.io/s/3y3nyrky4p.

you can read more about component Api  : http://react-popup.netlify.com/component-api/ 

Feel free to close this  issue if the code example work for your case.
