### ISSUE TITLE
Does not Working

### ISSUE THREAD

**Issue by Nathaniel-Santos** [yjose/reactjs-popup#246]
### Version
"2.0.4"

### Code Example
I have a PopUp page.js to make this component with this following code bellow:

const PopupExample = () => (
    <Popup trigger={<button>Trigger</button>} modal>
      {close => (
        <div>
          Content here
          <a className="close" onClick={close}> Mais; </a>
        </div>
      )}
    </Popup>
  );

And in some Page I import this one
Import PopupExample from '../path/from/compenent/here'

Then I add this PopupExample on onClick button returning <PopupExample />

### Expected Behavior
Trying to show a modal popup
### Actual Behavior
It shows nothing

**Comment by yjose** [comment]
can you provide a code sandbox example please
