### ISSUE TITLE
Manually close tooltip from within content

### ISSUE THREAD

**Issue by erezactionbar** [yjose/reactjs-popup#25]
### Test Case
https://codesandbox.io/s/n5q4zqw2n0

**Comment by kunokdev** [comment]
Why is it closed? Is it resolved? How do we actually close popup when clicked inside its content?

**Comment by stushurik** [comment]
@kunokdev thanks it was helpful

**Comment by dmatora** [comment]
@kunokdev that was helpful indeed

**Comment by dmatora** [comment]
@yjose would be really nice to have an option that does this
