### ISSUE TITLE
offsetX prop does not work as intended (or at all)

### ISSUE THREAD

**Issue by datner** [yjose/reactjs-popup#26]
### Version
1.1.1

### Test Case
[![Edit Reactjs-popup issue Template](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/01m615qqnv)

### Expected Behavior
offset the popup by 30px on the X axis

### Actual Behavior
no offset of the popup on the X axis

**Comment by yjose** [comment]
Hi @datner ,  thanks for your remarks 
issue fixed  reactjs-popup1.1.2 https://codesandbox.io/s/1v9w8vj7qj
