### ISSUE TITLE
Call onClose before modal dissapear

### ISSUE THREAD

**Issue by cesarm16** [yjose/reactjs-popup#28]
onClose should be called after modal dissapear if it is a controlled popup.

**Comment by yjose** [comment]
Hi @cesarm16, Can you provide more info with a sandbox use case !

**Comment by cesarm16** [comment]
i want to animate my modal after it is totally closed. I can't ,due the modal is unmounted before onClose is called, specially when i use closeOnDocumentClick.

**Comment by yjose** [comment]
Hi @cesarm16 , just fixed the issue reactjs-popup@1.1.4 , let's me know if this fix help you to animate your modal, feel free to share with me your example, we planned to add some default animation and we need some inspiration

**Comment by cesarm16** [comment]
Thank you!, just one problem...I think if you use it as a controlled component you should not set state isOpen to false until you change open prop to false.

**Comment by yjose** [comment]
@cesarm16  hmm,  can you open a PR, and we will see how it would work
