### ISSUE TITLE
Clicks propagate to the underlying control

### ISSUE THREAD

**Issue by adriano-repetti** [yjose/reactjs-popup#32]
If `trigger` is a link `<a>` and `on` is `click` then click triggers both the popup and the navigation to the link (or its `onclick`, if any). For example:

    <Popup trigger={<a onClick={this.handleClick}>click me</a>} />

Click to open is useful also for tooltip for touch devices (where hover isn't available and/or annoying/confusing for the user). We may mimic the hover behavior we see, for example, on Safari for iOS devices: first click always trigger the popup, second click when popup is open is bubbled down to the target control:

```
togglePopup(e) {
    if (e && !this.state.isOpen) {
        e.preventDefault();
    }
   
    // ...
}
```

We also need to change `closePopup()`:

```
closePopup(e) {
    if (e) {
        e.preventDefault();
    }

    // ...
}
```

**Comment by adriano-repetti** [comment]
@yjose thank you for your quick reply. You can reproduce it simply with:

```
const Test = () => {
    const handleClick = () => console.info("Clicked!");
    return <Popup on="click" trigger={<a onClick={handleClick}>click me</a>} />;
};
```

When you click on the link the popup correctly opens but the event isn't stopped and it also triggers the `onclick` on `<a>`. There are few use-cases for this, for example when using your component as tooltip (maybe with `on={[ "hover", "click" ]}`) in a touch device: first click to show the tooltip and second click to navigate the link (it's what, for example, Safari on iOS does, by default, with the `:hover` event).

**Comment by yjose** [comment]
fixed :

```jsx
<div onClick={() => console.log("I don't want to be called when trigger is clicked.")}>
    <Popup
      {...props}
      trigger={<button>Button Trigger</button>}
      onOpen={e => e.stopPropagation()}
      onClose={e => e.stopPropagation()}>
      <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo
        voluptas s lore Lorem ipsum dolor sit amet consectetur adipisicing
        elit. Nemo voluptas s loreLorem ipsum dolor sit amet consectetur
        adipisicing elit. Nemo voluptas s loreLorem ipsum dolor sit amet
        consectetur adipisicing elit. Nemo voluptas s lore
      </p>
    </Popup>
</div>
```
see #74

**Comment by TuanNamVu** [comment]
Hi @yjose, I think the typescript definitions have to be adjusted for onOpen or onClose, since an event is taken as an argument

**Comment by Bezmehrabi** [comment]
Hi, there's no event for `onClose`. version 2.0.4
