### ISSUE TITLE
popup arrowStyle css property "left" is been overridden

### ISSUE THREAD

**Issue by yashhy** [yjose/reactjs-popup#36]
While trying to custom `arrowStyle = { left: 20px }`  has no effect. 

CodeSandbox link where the `left: 50px` is ignored
https://codesandbox.io/s/pmp848njwx

I see its getting overridden by this line of code [here](https://github.com/yjose/reactjs-popup/blob/master/src/Utils.js#L76).

### The Issue : 

I set the `offsetX` props to move the popup content right (because that's my requirment) and now the arrow also moves right. So to centre align the arrow I use `arrowStyle` prop set the `left` property and that's been overridden.

#### Without OffsetX:
<img width="201" alt="without_offset" src="https://user-images.githubusercontent.com/4756393/45047187-f6153200-b095-11e8-92d5-b979ce2c75d2.png">

#### Without OffsetX:
<img width="208" alt="with_offset" src="https://user-images.githubusercontent.com/4756393/45047206-04634e00-b096-11e8-882d-6e7d92b8de0d.png">

### Suggestions:

1. Can we have a check if, the `left` property is explicitly set using `arrowStyle`, take the property from there without calculating [`arrowLeft`](https://github.com/yjose/reactjs-popup/blob/master/src/Utils.js#L76)
2. Calculate the `arrowLeft` with respect to `offsetX` props. Like
`arrowLeft = ((triggerBounding.width / 2) - offsetX) + "px";`. This would be bit buggy if the offsetX is set to very large values.
3.  Expose a extra prop `offsetArrowX` to specify the arrow left explicitly. 

First approach is bit more cleaner and explicit.

### Version
1.2.0

**Comment by yjose** [comment]
HI, @yashhy  good remark, 
Can you open a pull request using the first approach !!

**Comment by yashhy** [comment]
Sure will do 👍

**Comment by yashhy** [comment]
Hey @yjose, along with overriding arrow left, arrow top, content left and top can also be overridden?

So with that said,

The [current code](https://github.com/yjose/reactjs-popup/blob/master/src/Popup.js#L165) for `contentStyle` will be:

```
this.ContentEl.style.top = contentStyle.top || (cords.top - helper.top + "px");
this.ContentEl.style.left = contentStyle.left || (cords.left - helper.left + "px");
```
and [code](https://github.com/yjose/reactjs-popup/blob/master/src/Popup.js#L171) for `arrowLeft`

```
this.ArrowEl.style.top = arrowStyle.top || cords.arrowTop;
this.ArrowEl.style.left = arrowStyle.left || cords.arrowLeft;
```

Let me know your thoughts.

**Comment by yjose** [comment]
Hi @yashhy,  
For the first one the `this.ContentEl` must be positioned based on the helper cords.
we use the helper to position the tooltip on the right place and we use `offsetX`and `offsetY` to customize the position, so I think no need to update the `ContentEl` position part.

for the arrow, I think the best way is to customize position, we can use the arrowStyle position but must be related to the current position already calculated by the `calculatePosition` function.

**Comment by yjose** [comment]
@yashhy  any update here  or I can take the lead to fix it

**Comment by yashhy** [comment]
@yjose sorry man, was busy with other things. 

I was opening up a PR but it threw me this

Pushing to https://github.com/yjose/reactjs-popup.git
remote: Permission to yjose/reactjs-popup.git denied to yashhy.
fatal: unable to access 'https://github.com/yjose/reactjs-popup.git/': The requested URL returned error: 403

**Comment by yjose** [comment]
Hi @yashhy , you need to fork the repo ( GitHub top buttons ).
then you can update and push code to your forked repo and then you can open a PR from your GitHub repo.
let me know if you need more details
