### ISSUE TITLE
Tooltip cut off on smaller screens

### ISSUE THREAD

**Issue by pdewouters** [yjose/reactjs-popup#4]
Thanks for building this component. 
On small screeens, the tooltip can be cut off by the viewport, and doesn't follow the trigger element when resizing the window. See attached screenshot.
Here is a link to a demo of a "responsive" tooltip , to show you what I mean would be a good solution
https://osvaldas.info/examples/elegant-css-and-jquery-tooltip-responsive-mobile-friendly/
<img width="402" alt="screen shot 2018-03-21 at 11 13 58" src="https://user-images.githubusercontent.com/30460/37707007-627349c6-2cf9-11e8-8e13-adfb30fc18b9.png">

**Comment by yjose** [comment]
Hi, @pdewouters  thank you for your remarks :+1: 
For the first problem, I am working to position the tooltip in a smart way based on the tooltip boundaries and the viewport when the position prop doesn't exist.
Next, I think the second problem is not a major one, but of course, I will solve this problem soon.

**Comment by pdewouters** [comment]
Excellent, thank you very much
