### ISSUE TITLE
Popup's inside transformed elements do not have full screen overlay

### ISSUE THREAD

**Issue by dhruvparmar372** [yjose/reactjs-popup#46]
### Version
1.3.0

### Test Case
https://codesandbox.io/s/zm44w83zm

### Expected Behavior
Clicking outside the red box should close the popup.

### Actual Behavior
Clicking outside the red box doesn't close the popup. This is because `popup-overlay` which is positioned `fixed` when inside a parent having `transform` doesn't cover entire screen. If you remove `transform` from red box then expected behaviour would be occurring. 

### Possible Fix
Allow popup content to be rendered in a different root element than application's root. for e.g 
`<Popup popupRootID="popupRoot"></Popup>`. This could be achieved by using `Portal` rendering from `ReactDOM`.

**Comment by teagueash** [comment]
Totally agree with this. 
> Does not inject HTML outside your app root. 📦

Seems like a bad idea that creates all sorts of issues when trying to render popups/modals inside DOM elements. I'd love to hear the author of this library's reasoning/thoughts on that design choice.

**Comment by fromi** [comment]
I think it's related with this webkit bug: https://stackoverflow.com/questions/2637058/positions-fixed-doesnt-work-when-using-webkit-transform

**Comment by yjose** [comment]
we implement v2 using portal which fixes the issue
