### ISSUE TITLE
Feature Request: Popup recalculates position when window is resized

### ISSUE THREAD

**Issue by ThePaulMcBride** [yjose/reactjs-popup#48]
It would be great to be able to pass a `repositionOnResize` prop that would recalculate the position of the popup when the widow width and possibly height changes.

Another approach would be to expose the reposition function so that components that consume this component could tell the popup when to recalculate position.

**Comment by yjose** [comment]
Hi @ThePaulMcBride , thanks for your remark, this problem is on my radar, it will be fixed ASAP
