### ISSUE TITLE
Feature request: disabled property

### ISSUE THREAD

**Issue by raRaRa** [yjose/reactjs-popup#49]
Hi.

I want to suggest a new property for `<Popup />` which is `disabled`. I've run into an issue where I have a tooltip displayed when the mouse is hovering over a button, and when I click on the button I change the opacity of the button to `0`. But unfortunately the tooltip will still show up, which is the expected behavior.

That's why I want to suggest the new prop: `disabled`.

When `disabled` is set as a prop for `<Popup />`, then the tooltip will be removed if it's already displayed, and it won't show up when hovering over a disabled `<Popup />`.

I hope this gets implemented, and I could probably help out if there's interest.

Thanks!

**Comment by yjose** [comment]
HI @raRaRa , Good remark.
I suggest To open a new PR for this if you have some time of course.
The implementation would be simple I think.
lets me know if you have any problem

**Comment by raRaRa** [comment]
Great to hear! And excellent job, this is the only tooltip library that behaves and works like it should 🥇 

I have a problem when I try to `yarn start` after `yarn install`. I get this error: 

```
$ parcel serve ./stories/index.html --no-autoinstall
Server running at http://localhost:1234
×  C:\git\reactjs-popup\stories\index.js: Plugin/Preset files are not allowed to export objects, only functions. In C:\git\reactjs-popup\node_modules\babel-preset-react\lib\index.js
```

I'm wondering if

**Comment by yjose** [comment]
let's me check

**Comment by raRaRa** [comment]
Still same issue :( I also tried removing yarn.lock among the steps you mentioned.

**Comment by yjose** [comment]
Just got it. 
look like parcel Now, support the babel 7.  so the old config tries to use the old presets.
you just need to update the the `.babelrc` file. 
```
"presets": [
    "@babel/env",
    "@babel/react"
  ],
```

**Comment by raRaRa** [comment]
Thanks, that did the trick.

I have implemented the first version of the `disabled` prop here: https://github.com/raRaRa/reactjs-popup

I also created a story for it.

**Comment by yjose** [comment]
cool 👍 , 
*Need to add a test case for it if you are familiar with jest then open a PR.
* Update the component API  https://github.com/yjose/reactjs-popup/blob/master/docs/src/markdown/componentApi.md 
I will review it ASAP.

**Comment by yjose** [comment]
Yeah of Course: https://github.com/yjose/reactjs-popup/blob/master/__test__/index.test.js 

you will notice that the build from your new PR was failed, it's related to Docs App just ignore it, I am migrating to gatsbyjs over react-static.

**Comment by raRaRa** [comment]
Hi, please review my PR here: https://github.com/yjose/reactjs-popup/pull/50

**Comment by raRaRa** [comment]
Hey @yjose - any update on this? Thanks!
