### ISSUE TITLE
Feature/Bug:  Tooltip behavior on individual table cells.

### ISSUE THREAD

**Issue by ChrisLincoln** [yjose/reactjs-popup#5]
### Version
1.0.5

### Test Case
https://codesandbox.io/s/yqp74xwo5j

### Expected Behavior
When a table-like structure is used and tool-tips are desired for each cell, the tool-tip should appear for each cell.

### Actual Behavior
The tooltip appears for every other cell.  The enter/leave logic requires some sort of intermediate "non-triggered" space.  

I have attempted to a) eliminate the timeout timer, b) give enter and exit it's own timeout timer.  Neither worked.  By placing console.log() messages in the code, I think the renderTrigger() code happens after onMouseEnter in the cases where the tool tip does not appear.

This issue could be considered a feature request or a bug.

**Comment by yjose** [comment]
Hi @ChrisLincoln 
Thank you for this great explication. it looks like it's a bug when we don't have a non-triggered space between tow triggers.
I will work on this soon.
Feel free to submit a pull request if you have any ideas !!

**Comment by yjose** [comment]
it looks like the problem is caused by the popup overlay, so to fix the problem the overlay will be excluded by default on hover.
Done!!

**Comment by ChrisLincoln** [comment]
Thank you @yjose!  Just to close the circle, I applied the fix from 1.0.7 to my app and now get the expected behavior.

**Comment by necheporenko** [comment]
Is it possible to change this default behavior?
Because in my case, I want to show an overlay on hovering elements.
