### ISSUE TITLE
Previous Popup content  not  closing  when using  keyboard tab to focus enter ?

### ISSUE THREAD

**Issue by itjayaprakash** [yjose/reactjs-popup#60]
i have added multiple button each button have some popup content  
i enter the first button. it's displaying some content fine.  then without any mouse click  after 
i enter the another button it's also displaying the popup content... the two popup content is showing....
previous popup content is not removing....

if u mouse click or esc press only remove the popup content...

Thanks,

**Comment by yjose** [comment]
Hi @itjayaprakash , thanks for your remarks,
if you can please provide an example describing the issue  using the reactjs-popup code sandbox example https://codesandbox.io/s/n5q4zqw2n , it would be very helpful 

thanks

**Comment by itjayaprakash** [comment]
Hi yjose,
               I am developing my project everything as per  a11y  with  WCAG Guideline... 
"reactjs-popup"  is not followed as per WCAG !  so i am facing some issue this component. 

I have created  example here  can you please check. not closing previous modal already opened still showing after new modal enter. i attached sample here.

https://codesandbox.io/s/40o5k83m1w


<img src="https://i.ibb.co/6b43htx/Sample.png"/>

thanks

**Comment by yjose** [comment]
hi @itjayaprakash 
This is an accessibility issue and I think @ndelangen can help on this.
any ideas @ndelangen ?

**Comment by yjose** [comment]
hi @itjayaprakash 
This is an accessibility issue and I think @ndelangen can help on this.
any ideas @ndelangen ?

**Comment by mcvladthegoat** [comment]
@yjose Is it ok if I'll try to solve this bug?

**Comment by yjose** [comment]
Yeah sure, Go for it @mcvladthegoat

**Comment by mcvladthegoat** [comment]
@yjose Cool :)

**Comment by mcvladthegoat** [comment]
@itjayaprakash i finished this feature. Waiting for PR approve.
You can try it here (forked repo): https://github.com/mcvladthegoat/reactjs-popup/tree/feat/popup_blur_tab
So if you need to close popup when Tab key pressed, just add prop `closeOnKeyboardBlur={true}`to `<Popup />`
For example (according to your sandbox https://codesandbox.io/s/40o5k83m1w):
```js 
<Popup
     closeOnKeyboardBlur={true}
     trigger={<button> Trigger</button>}
     position="right center"
>
     <div>Popup content 2</div>
</Popup>
```

**Comment by yjose** [comment]
with v2 this should work as expected
