### ISSUE TITLE
Add support for CSS classes

### ISSUE THREAD

**Issue by iljapanic** [yjose/reactjs-popup#61]
Currently, if you want to style the popup content you need to pass a styles object to `contentStyle`.

It would be great if we could use `className` or something like `customClass` to style the content via CSS classes instead.

**Comment by gajus** [comment]
Was this closed without a solution?

This does not appear to be supported at the moment.

**Comment by RainbowAsteroids** [comment]
You can address the popup itself via `.popup-content` and use `!important` to overwrite the inline styles. It's not perfect, and it won't let you append extra classes, (so you can't do `.popup-content.modal`) but it's bettter than nothing.
