### ISSUE TITLE
Example site example doesn't Work

### ISSUE THREAD

**Issue by EunsungKoh** [yjose/reactjs-popup#69]
I tried to visit your example site https://react-popup.elazizi.com/ and https://react-popup.netlify.com/ both, but I couldn't be there.

`This site can’t be reached react-popup.elazizi.com’s server IP address could not be found.
DNS_PROBE_FINISHED_NXDOMAIN`

This is only what I got in the example site.

Any help much appreciated..

**Comment by yjose** [comment]
Hi @eunsugkoh, look like it's a netlify DNS issue for a while, i just checked and it's work like a charm. Please verify and close the issue in case.

**Comment by EunsungKoh** [comment]
Thanks! I checked it works. :grin:
