### ISSUE TITLE
Popup being covered by a parent that has overflow:hidden style

### ISSUE THREAD

**Issue by tweeklabs-isaac** [yjose/reactjs-popup#70]
When you set the parent of the Popup to have position:relative and the parent's has overflow hidden, the Popup is being covered when you try to show it.

See example: https://codesandbox.io/s/21wz7z94lp

Is there a work around with this? Maybe set an option to append the Popup node as last element on #root?

Version: 1.3.2
Test Case: https://codesandbox.io/s/21wz7z94lp
Wanted Behavior: Popup to not be covered by parent.
Actual Behavior: Popup being covered by Parent

**Comment by mtrsklnkvMM** [comment]
I would be interested in having a fix or a enhancement for that as well

**Comment by mnmistake** [comment]
this is really an issue I cannot even solve it with Portal

**Comment by yjose** [comment]
Hi @tweeklabs-isaac, I am not seeing Popup being covered by Parent in your example, can you check ?

**Comment by tweeklabs-isaac** [comment]
@yjose yeah i'm not seeing it either now. it might have been fixed with the updates you made since i created this ticket. I'll update my project dependency and I'll close this ticket as soon as I see if its already working
