### ISSUE TITLE
Custom media queries

### ISSUE THREAD

**Issue by fdsero** [yjose/reactjs-popup#72]
Hey there!
Love the package, is there any way to add in custom media queries depending on screen width. I'd like to readjust the content style depending on device width. Currently we're using styled components on the front end.

Any help with this would be awesome, thanks!

- Frank

**Comment by yjose** [comment]
Hi @fdsero 
`className` styling is supported on the last version [1.4.0](https://github.com/yjose/reactjs-popup/releases/tag/V1.4.0) so you can use Custom media queries
