### ISSUE TITLE
Overlay not blurring, instead the modal gets blurred.

### ISSUE THREAD

**Issue by janvandijke** [yjose/reactjs-popup#77]
When I add an object to the prop `overlayStyle` with` filter: "blur(1px)"`, what happens is that only the modal itself gets blurred, but not the background/overlay.

```
<Popup
   open={this.state.showModal} onClose={this.closeModal} modal closeOnDocumentClick contentStyle= 
   {modalContentStyle} overlayStyle={modalOverlayStyle} >
    <div className="modalContent">
    </div>   
   </Popup>

```

The object with the react CSS:

```
        const modalOverlayStyle = {
            filter: "blur(1px)"
        }
```

**Comment by yjose** [comment]
hi @janvandijke,
I think this is a natural behavior because of popup architecture.  the popup content is a child of popup overlay div which means that the blur effect will propagate to the popup content

**Comment by janvandijke** [comment]
I understand, thanks.

**Comment by robbertkl** [comment]
Instead you can do this:

```
        const modalOverlayStyle = {
            backdropFilter: "blur(1px)"
        }
```

That way, it will only apply to the content behind the overlay. Please note browser support for CSS backdrop-filter might be a bit less, but it's a good solution where the blur is not essential.
