### ISSUE TITLE
add all possible positions in case of typescript

### ISSUE THREAD

**Issue by pun12189** [yjose/reactjs-popup#82]
### Version
1.3.2

### Test Case
no test cases

### Expected Behavior
i want this in indes.d.ts file to be merged with new release. Regarding this there is this commit 833b93c060b3b72d02dec0b3ebd7259dec03314d is present

type Position = 'top left' | 'top center' | 'top right' |
                  'right top' | 'right center' | 'right bottom' |
                  'bottom left' | 'bottom center' | 'bottom right' |
                  'left top' | 'left center' | 'left bottom';
### Actual Behavior
Currently this code is present in your current release.
type Position = 'top left' | 'top right' | 'bottom right' | 'bottom left' | 'right center' | 'left center' | 'top center' | 'bottom center';

**Comment by yjose** [comment]
I don't think soo @pun12189 , the Position type has the correct enum, can you check again?
