### ISSUE TITLE
About Subscription

### ISSUE THREAD

**Issue by leon2835** [yjose/reactjs-popup#83]
Hi there, let's say if I'm using the PopUp library that you provide and it will pop up a dialog as usual.
But my current problem is, if i'm subscribing websocket inside <TabsComponent/>. when I close the popup it will show  "Can't perform a React state update on an unmounted component." even that i already implement following code inside <TabsComponent/>
 componentDidMount() {
        this._isMounted = true;
}

componentWillUnmount() {
        this._isMounted = false;}

Any ideas how to solve this? Thank You.

**Comment by yjose** [comment]
Can you provide a simple demo of your use case using the codesandbox  template

**Comment by leon2835** [comment]
Sorry that i try to used codesandbox/ codepen but is not working. Just assume that when I implement
*  <Popup trigger={<button className="float-right" >{i18n.t("view_statistic")} </button>} modal>
      {close => (
        <div >
          <div className="close" onClick={close}>
            &times;
      </div>
          <TabsComponent /> <<<< new js file //import TabsComponent from "../Components/Tabs"
        </div>
      )}
    </Popup>
* Then under TabsComponent is a class that contain constructor, render,  componentDidMount and 
   componentWillUnmount with this.isMounted = true and false.
* Under componentDidMount contain a timer or somethings that will keep running
* And if i close the tabs, and i click f12, it will show:
  index.js:1437 Warning: Can't perform a React state update on an unmounted component. This is a no- 
  op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous 
  tasks in the componentWillUnmount method.
*Even that i already put componentDidMount and componentWillUnmount inside TabsComponent.js
*Hope you can understand that. Thank You

**Comment by yjose** [comment]
To be honest I can’t understand what you’re trying to do. but you can use `onClose` to fix to delete any  Subscription and I guess your problem is related to `TabsComponent.js` implementation not the Popup component itself

**Comment by MANTENN** [comment]
Am encountering this issue with preact.
