### ISSUE TITLE
Using custom component as trigger does not work

### ISSUE THREAD

**Issue by kevinlaw91** [yjose/reactjs-popup#84]
Using custom components such as `<FancyButton />` as `trigger` does not work

```jsx

function CustomButton () {
  return <button>Custom</button>;
}

<Popup trigger={<CustomButton />}>
  <div>Not Work</div>
</Popup>
```

### Version
1.3.2

### Test Case

https://codesandbox.io/s/9jx6mx22w

### Expected Behavior
Popup will show but it doesn't

**Comment by yjose** [comment]
Hi @kevinlaw91 
You just need to pass missed props to your trigger like the following : 
```jsx
function CustomButton (props) {
  return <button {...props}>Custom</button>;
}

<Popup trigger={(props) => <CustomButton {...props}  />}>
  <div>Not Work</div>
</Popup>
```

https://codesandbox.io/s/2lv3wo9ly
