### ISSUE TITLE
Animation API support timing

### ISSUE THREAD

**Issue by NinoMaj** [yjose/reactjs-popup#87]
I've seen in documentation that Animation API will eventually be supported, do you maybe have estimation when will that be? Is that something in the works already?

**Comment by yjose** [comment]
Yeah @NinoMaj , I am planning to support Animation API after upgrading the Popup to use React Portal API so we can add Animation without limitation.
with the current implementation, we have some issue with CSS `transform` properties. 
I think I need 3weeks to a month to make this work and I will be happy if you have some ideas on how the animation API would look like?

**Comment by AdamLee321** [comment]
Is there any progress on the Animation API? I am trying to do a simple fadeInUp but can't get it to work. Any ideas how to get it to work?
