### ISSUE TITLE
different content for different triggers

### ISSUE THREAD

**Issue by rtm7777** [yjose/reactjs-popup#88]
Hello, I have feature request/question

I want to show different content on different actions
Eg. on hover I want to show some simple text, but on click I want to show some list
I've tried this:
``` 
  <Popup
    trigger={open => (
      <button className="button">Trigger - {open ? "Opened" : "Closed"}</button>
    )}
    on={["hover", "click"]}
    position="right center"
    closeOnDocumentClick
    children={props => {
      return <span>{JSON.stringify(props)}</span>;
    }}
  />
```

but looks like it's not possible
so this can be a question if I did it wrong or a feature request

Thanks!

**Comment by avin-kavish** [comment]
What do you think the syntax should look like to support this?

**Comment by rtm7777** [comment]
It can work as on my example: have some prop to accept function and return event type so I can decide what I need to render according to it, this is first thing on my mind, I can try to find some other options

**Comment by avin-kavish** [comment]
No need, render prop sounds good. To elaborate on your example, 
```jsx
  <Popup
    trigger={open => (
      <button className="button">Trigger - {open ? "Opened" : "Closed"}</button>
    )}
    on={["hover", "click"]}
    position="right center"
    closeOnDocumentClick
    render={({ on, ...props }) => {
      switch (on) {
        case 'hover':
          return <Foo />;
        case 'click':
           return <Bar />;
      }
    }}
  />
```

Another pattern would be to pass a function as children.

```jsx
  <Popup
    trigger={open => (
      <button className="button">Trigger - {open ? "Opened" : "Closed"}</button>
    )}
    on={["hover", "click"]}
    position="right center"
    closeOnDocumentClick
   >
   {({ on, ...props }) => {
      switch (on) {
        case 'hover':
          return <Foo />;
        case 'click':
           return <Bar />;
      }
    }}
   </Popup> 
```
Any preference? In both cases, do you think props should be all the props passed to `Popup`, just the `on` event or specific props ?

Note: By `on`, I'm referring to the event that triggered the popup as opposed to the `on` prop passed to the component.

**Comment by rtm7777** [comment]
For my case it's ok to have only `on`, but maybe for some more specific case it's better to have other props (of course if it won't increase complexity of the package), so if those props are dynamic we can change some content behavior
I saw something similar on Formik's package
