### ISSUE TITLE
Position: relative permanently set on trigger elements

### ISSUE THREAD

**Issue by Mantower** [yjose/reactjs-popup#92]
### Version
v1.4.1

### Test Case
https://codesandbox.io/embed/polished-sun-nzz8o

### Expected Behavior
When one tooltip is open, you should not be able to interact with anything else in the DOM. This allows a tooltip to close if a user clicks anywhere outside of the tooltip.

### Actual Behavior
When rendering several tooltips, any tooltip trigger that has previously been rendered is keeping its element style "position: relative". This means that when I have one tooltip open, I can still interact with other tooltip triggers outside of the current element.

### Further explanation
I provided a text case above. When the page is initially rendered, neither of the trigger divs have any position set on their element styling. However, once I have opened them once, the element styling changes to "position: relative". This is kept even if I close the popup. 

To illustrate this, do the following steps.

1. Open tooltip Two.
2. Close tooltip Two.
3. Open tooltip One.
4. It is now possible to open tooltip Two even though tooltip One is in focus. Doing so opens both tooltips, which might lead to tooltips covering each other. 

### Potential fix
Reset the styling of the trigger element (perhaps static?) when closing the tooltip.

**Comment by yjose** [comment]
Good catch @Mantower, and perfect explanation.
we add a `relative` to trigger to simplify the calculation for the tooltip position.
I thought that it wouldn't affect the popup behavior but it's not the case, I think we need to reset the position onClose. 
lets me see if you can open a PR to fix it.

**Comment by Mantower** [comment]
I'll see if I'll be able to find a solution. I'll get back to you.

**Comment by Mantower** [comment]
@yjose Got any comments on the Pull Request?

**Comment by avin-kavish** [comment]
> I thought that it wouldn't affect the popup behavior but it's not the case, I think we need to reset the position onClose.

You haven't done what he has asked you to do
